import type { Metadata } from 'next'
import { Providers } from './providers'
import GlobalStyles from '@/styles/global'

export const metadata: Metadata = {
  title: 'Won Games',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalStyles />
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
